# Generated by Django 4.2.30 on 2026-08-29 16:10

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Описание"
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ключевые слова"
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(blank=True, verbose_name="Каноническая ссылка"),
                ),
                (
                    "robots_noindex",
                    models.BooleanField(
                        default=False, verbose_name="Запретить индексацию"
                    ),
                ),
                (
                    "robots_nofollow",
                    models.BooleanField(
                        default=False, verbose_name="Запретить следование"
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="OG заголовок"
                    ),
                ),
                (
                    "og_description",
                    models.TextField(
                        blank=True, max_length=300, verbose_name="OG описание"
                    ),
                ),
                (
                    "twitter_card_type",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("summary_large_image", "Summary Large Image"),
                        ],
                        default="summary_large_image",
                        max_length=20,
                        verbose_name="Тип Twitter карты",
                    ),
                ),
                (
                    "subject_code",
                    models.CharField(max_length=10, verbose_name="Код предмета"),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Начинающий"),
                            ("intermediate", "Средний"),
                            ("advanced", "Продвинутый"),
                        ],
                        max_length=20,
                        verbose_name="Уровень сложности",
                    ),
                ),
                (
                    "introduction",
                    wagtail.fields.RichTextField(verbose_name="Введение в предмет"),
                ),
                (
                    "curriculum",
                    wagtail.fields.StreamField(
                        [
                            (
                                "module",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                label="Название модуля"
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.blocks.RichTextBlock(
                                                "Описание модуля"
                                            ),
                                        ),
                                        (
                                            "lessons",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "lesson_title",
                                                            wagtail.blocks.CharBlock(
                                                                label="Урок"
                                                            ),
                                                        ),
                                                        (
                                                            "lesson_content",
                                                            wagtail.blocks.RichTextBlock(
                                                                "Содержание"
                                                            ),
                                                        ),
                                                    ]
                                                )
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="LaboratoryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Описание"
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ключевые слова"
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(blank=True, verbose_name="Каноническая ссылка"),
                ),
                (
                    "robots_noindex",
                    models.BooleanField(
                        default=False, verbose_name="Запретить индексацию"
                    ),
                ),
                (
                    "robots_nofollow",
                    models.BooleanField(
                        default=False, verbose_name="Запретить следование"
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="OG заголовок"
                    ),
                ),
                (
                    "og_description",
                    models.TextField(
                        blank=True, max_length=300, verbose_name="OG описание"
                    ),
                ),
                (
                    "twitter_card_type",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("summary_large_image", "Summary Large Image"),
                        ],
                        default="summary_large_image",
                        max_length=20,
                        verbose_name="Тип Twitter карты",
                    ),
                ),
                (
                    "lab_type",
                    models.CharField(
                        choices=[
                            ("music", "Музыкальная"),
                            ("physics", "Физическая"),
                            ("other", "Другая"),
                        ],
                        max_length=50,
                        verbose_name="Тип лаборатории",
                    ),
                ),
                (
                    "equipment",
                    wagtail.fields.StreamField(
                        [
                            (
                                "equipment_item",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "name",
                                            wagtail.blocks.CharBlock(
                                                label="Название оборудования"
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.blocks.RichTextBlock("Описание"),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=False
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "experiments",
                    wagtail.fields.StreamField(
                        [
                            (
                                "experiment",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                label="Название эксперимента"
                                            ),
                                        ),
                                        (
                                            "objective",
                                            wagtail.blocks.TextBlock(
                                                label="Цель эксперимента"
                                            ),
                                        ),
                                        (
                                            "methodology",
                                            wagtail.blocks.RichTextBlock("Методология"),
                                        ),
                                        (
                                            "results",
                                            wagtail.blocks.RichTextBlock(
                                                "Ожидаемые результаты"
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="InstituteIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Описание"
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ключевые слова"
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(blank=True, verbose_name="Каноническая ссылка"),
                ),
                (
                    "robots_noindex",
                    models.BooleanField(
                        default=False, verbose_name="Запретить индексацию"
                    ),
                ),
                (
                    "robots_nofollow",
                    models.BooleanField(
                        default=False, verbose_name="Запретить следование"
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="OG заголовок"
                    ),
                ),
                (
                    "og_description",
                    models.TextField(
                        blank=True, max_length=300, verbose_name="OG описание"
                    ),
                ),
                (
                    "twitter_card_type",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("summary_large_image", "Summary Large Image"),
                        ],
                        default="summary_large_image",
                        max_length=20,
                        verbose_name="Тип Twitter карты",
                    ),
                ),
                (
                    "introduction",
                    wagtail.fields.RichTextField(blank=True, verbose_name="Введение"),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
