# Generated by Django 4.2.30 on 2026-08-29 20:00

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("institute", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectpage",
            name="curriculum",
            field=wagtail.fields.StreamField(
                [
                    (
                        "module",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(label="Название модуля"),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.TextBlock(label="Описание модуля"),
                                ),
                                (
                                    "lessons",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "lesson_title",
                                                    wagtail.blocks.CharBlock(
                                                        label="Урок"
                                                    ),
                                                ),
                                                (
                                                    "lesson_content",
                                                    wagtail.blocks.TextBlock(
                                                        label="Содержание"
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
