# Generated by Django 4.2.30 on 2026-08-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_newspage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspage",
            name="summary",
            field=models.CharField(
                blank=True,
                help_text="Отображается в списке новостей и в поиске.",
                max_length=300,
                verbose_name="Краткое описание",
            ),
        ),
        migrations.AlterField(
            model_name="newspage",
            name="date",
            field=models.DateField(
                blank=True,
                help_text="Дата публикации новости (задаётся вручную).",
                null=True,
                verbose_name="Дата публикации",
            ),
        ),
    ]
