# Generated by Django 4.2.30 on 2026-08-29 20:03

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manifestpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="title")),
                    ("paragraph", wagtail.blocks.TextBlock()),
                    ("quote", wagtail.blocks.BlockQuoteBlock()),
                    (
                        "list",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.CharBlock(label="Пункт")
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
