# Generated by Django 4.2.30 on 2026-08-30 03:16

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_alter_emblempage_emblem_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codexpage",
            name="articles",
            field=wagtail.fields.StreamField(
                [
                    (
                        "article",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(label="Заголовок статьи"),
                                ),
                                (
                                    "content",
                                    wagtail.blocks.TextBlock(label="Содержание статьи"),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
