# Generated by Django 4.2.30 on 2026-08-31 18:08

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("content", "0004_alter_codexpage_articles"),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ключевые слова"
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(blank=True, verbose_name="Каноническая ссылка"),
                ),
                (
                    "robots_noindex",
                    models.BooleanField(
                        default=False, verbose_name="Запретить индексацию"
                    ),
                ),
                (
                    "robots_nofollow",
                    models.BooleanField(
                        default=False, verbose_name="Запретить следование"
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="OG заголовок"
                    ),
                ),
                (
                    "og_description",
                    models.TextField(
                        blank=True, max_length=300, verbose_name="OG описание"
                    ),
                ),
                (
                    "twitter_card_type",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("summary_large_image", "Summary Large Image"),
                        ],
                        default="summary_large_image",
                        max_length=20,
                        verbose_name="Тип Twitter карты",
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="О библиотеке"
                    ),
                ),
                (
                    "resources",
                    wagtail.fields.StreamField(
                        [
                            (
                                "resource",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(label="Название"),
                                        ),
                                        (
                                            "author",
                                            wagtail.blocks.CharBlock(
                                                label="Автор", required=False
                                            ),
                                        ),
                                        (
                                            "resource_type",
                                            wagtail.blocks.CharBlock(
                                                label="Тип", required=False
                                            ),
                                        ),
                                        (
                                            "url",
                                            wagtail.blocks.URLBlock(
                                                label="Ссылка", required=False
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.blocks.TextBlock(
                                                label="Описание", required=False
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="JournalPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ключевые слова"
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(blank=True, verbose_name="Каноническая ссылка"),
                ),
                (
                    "robots_noindex",
                    models.BooleanField(
                        default=False, verbose_name="Запретить индексацию"
                    ),
                ),
                (
                    "robots_nofollow",
                    models.BooleanField(
                        default=False, verbose_name="Запретить следование"
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="OG заголовок"
                    ),
                ),
                (
                    "og_description",
                    models.TextField(
                        blank=True, max_length=300, verbose_name="OG описание"
                    ),
                ),
                (
                    "twitter_card_type",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("summary_large_image", "Summary Large Image"),
                        ],
                        default="summary_large_image",
                        max_length=20,
                        verbose_name="Тип Twitter карты",
                    ),
                ),
                (
                    "volume",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Том/Номер"
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата издания"
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Описание выпуска"
                    ),
                ),
                (
                    "articles",
                    wagtail.fields.StreamField(
                        [
                            (
                                "article",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                label="Название статьи"
                                            ),
                                        ),
                                        (
                                            "authors",
                                            wagtail.blocks.CharBlock(
                                                label="Авторы", required=False
                                            ),
                                        ),
                                        (
                                            "abstract",
                                            wagtail.blocks.TextBlock(
                                                label="Аннотация", required=False
                                            ),
                                        ),
                                        (
                                            "url",
                                            wagtail.blocks.URLBlock(
                                                label="Ссылка", required=False
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
