# Generated by Django 4.2.30 on 2026-09-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_librarypage_journalpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalpage",
            name="source_url",
            field=models.URLField(
                blank=True,
                default="https://neoallunity.github.io/allunity-zhurnaly",
                verbose_name="Источник",
            ),
        ),
        migrations.AddField(
            model_name="librarypage",
            name="source_url",
            field=models.URLField(
                blank=True,
                default="https://neoallunity.github.io/allunity-diskussii",
                verbose_name="Источник",
            ),
        ),
    ]
