# Generated by Django 4.2.30 on 2026-08-29 16:10

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscussionPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Описание"
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ключевые слова"
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(blank=True, verbose_name="Каноническая ссылка"),
                ),
                (
                    "robots_noindex",
                    models.BooleanField(
                        default=False, verbose_name="Запретить индексацию"
                    ),
                ),
                (
                    "robots_nofollow",
                    models.BooleanField(
                        default=False, verbose_name="Запретить следование"
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="OG заголовок"
                    ),
                ),
                (
                    "og_description",
                    models.TextField(
                        blank=True, max_length=300, verbose_name="OG описание"
                    ),
                ),
                (
                    "twitter_card_type",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("summary_large_image", "Summary Large Image"),
                        ],
                        default="summary_large_image",
                        max_length=20,
                        verbose_name="Тип Twitter карты",
                    ),
                ),
                (
                    "topic",
                    models.CharField(max_length=200, verbose_name="Тема обсуждения"),
                ),
                ("author", models.CharField(max_length=100, verbose_name="Автор")),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="Закреплено"),
                ),
                (
                    "is_locked",
                    models.BooleanField(default=False, verbose_name="Заблокировано"),
                ),
                (
                    "initial_post",
                    wagtail.fields.RichTextField(verbose_name="Начальное сообщение"),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="DiscussionIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Описание"
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ключевые слова"
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(blank=True, verbose_name="Каноническая ссылка"),
                ),
                (
                    "robots_noindex",
                    models.BooleanField(
                        default=False, verbose_name="Запретить индексацию"
                    ),
                ),
                (
                    "robots_nofollow",
                    models.BooleanField(
                        default=False, verbose_name="Запретить следование"
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="OG заголовок"
                    ),
                ),
                (
                    "og_description",
                    models.TextField(
                        blank=True, max_length=300, verbose_name="OG описание"
                    ),
                ),
                (
                    "twitter_card_type",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("summary_large_image", "Summary Large Image"),
                        ],
                        default="summary_large_image",
                        max_length=20,
                        verbose_name="Тип Twitter карты",
                    ),
                ),
                (
                    "rules",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Правила обсуждений"
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
